
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/usersatoshi/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/home/usersatoshi/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/home/usersatoshi/.vscode-server/cli/servers/Stable-994fd12f8d3a5aa16f17d42c041e5809167e845a/server/bin/remote-cli/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
    searched_directories:
      - "/home/usersatoshi/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/home/usersatoshi/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/home/usersatoshi/.vscode-server/cli/servers/Stable-994fd12f8d3a5aa16f17d42c041e5809167e845a/server/bin/remote-cli/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/usersatoshi/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand"
        - "/home/usersatoshi/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli"
        - "/home/usersatoshi/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand"
        - "/home/usersatoshi/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli"
        - "/home/usersatoshi/.vscode-server/cli/servers/Stable-994fd12f8d3a5aa16f17d42c041e5809167e845a/server/bin/remote-cli"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.18.2-2-cachyos - x86_64
...
